name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.target.os }}
    timeout-minutes: 360
    strategy:
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
          - { name: Windows, os: windows-latest, triple: x86_64-pc-windows-msvc }
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up rust
        run: |
          rustup toolchain install 1.83.0 --profile minimal --no-self-update
          rustup default 1.83.0-${{ matrix.target.triple }}
          rustup --version
          rustc --version
          cargo --version
      - name: Run tests
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up rust
        run: |
          rustup toolchain install 1.83.0 --profile minimal --no-self-update
          rustup default 1.83.0-x86_64-unknown-linux-gnu
          rustup --version
          rustc --version
          cargo --version
      - name: Set up clippy
        run: |
          rustup component add clippy
      - name: Run clippy
        run: cargo clippy
